table Sheet2
	lineageTag: 1da0dea1-1d7a-4a56-884c-f358ab383e4f

	column Column1
		dataType: string
		lineageTag: 1fc2aa10-ee29-40fc-95f3-e3b79cfef3a8
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: f78a84f3-322d-41f6-982a-ea8a04aa082d
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Sheet2 = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\system1028\Downloads\Bookings-100000-Rows.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Sheet2", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

